config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'
  get 'memos/show'
  get 'memos/new'
  get 'memos/create'
  get 'memos/edit'
  get 'memos/update'
  get 'memos/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :memos
root to: 'memos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memos = Memo.all
  end
  

  def show
    @memo = Memo.find(params[:id])
  end
  

  def new
    @memo = Memo.new
  end
  

  def create
    @memo = Memo.new(memo_params)
  
    if @memo.save
      redirect_to @memo, notice: 'Memo was successfully created.'
    else
      render :new
    end
  end
  

  def edit
    @memo = Memo.find(params[:id])
  end
  

  def update
    @memo = Memo.find(params[:id])
  
    if @memo.update(memo_params)
      redirect_to @memo, notice: 'Memo was successfully updated.'
    else
      render :edit
    end
  end
  

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
  
    redirect_to memos_url, notice: 'Memo was successfully destroyed.'
  end

  private

def memo_params
  params.require(:memo).permit(:title, :content)
end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/create.html.erb
<h1>Memos#create</h1>
<p>Find me in app/views/memos/create.html.erb</p>

app/views/memos/destroy.html.erb
<h1>Memos#destroy</h1>
<p>Find me in app/views/memos/destroy.html.erb</p>

app/views/memos/edit.html.erb
<!-- app/views/memos/edit.html.erb -->

<h1>メモ編集</h1>

<%= form_with(model: @memo, url: memo_path(@memo), method: :patch) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit '更新する' %>
  </div>
<% end %>

<%= link_to '戻る', @memo %>

app/views/memos/index.html.erb
<!-- app/views/memos/index.html.erb -->

<h1>メモ一覧</h1>

<% @memos.each do |memo| %>
  <h3><%= link_to memo.title, memo %></h3>
  <p><%= memo.content %></p>
<% end %>

<%= link_to '新規作成', new_memo_path %>

app/views/memos/new.html.erb
<!-- app/views/memos/new.html.erb -->

<h1>新規メモ作成</h1>

<%= form_with(model: @memo, url: memos_path) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit '作成する' %>
  </div>
<% end %>

<%= link_to '戻る', memos_path %>

app/views/memos/show.html.erb
<!-- app/views/memos/show.html.erb -->

<h1><%= @memo.title %></h1>
<p><%= @memo.content %></p>

<%= link_to '編集', edit_memo_path(@memo) %> |
<%= link_to '削除', @memo, method: :delete, data: { confirm: '削除してもよろしいですか？' } %> |
<%= link_to '戻る', memos_path %>

app/views/memos/update.html.erb
<h1>Memos#update</h1>
<p>Find me in app/views/memos/update.html.erb</p>